### ISSUE TITLE
Download link has been changed

### ISSUE THREAD

**Issue by trtuanpham** [Vitty85/vimm-client-miyoo#1]
please update it from "https://download3.vimm.net/download/?mediaId=$mediaId" to "https://download2.vimm.net/?mediaId=$mediaId"

**Comment by Vitty85** [comment]
Actually they should be both tried:

get_gameName() {
	url=https://download2.vimm.net/download/?mediaId=$mediaId
	headers=$(curl -sI -X GET -H "Referer: https://vimm.net/vault/$vaultId" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" --insecure $url)
	gameName=$(echo "$headers" | grep -o -E "filename=.*" | cut -d'=' -f2 | cut -d'"' -f2)
	if [ "$gameName" = "" ]; then
		url=https://download3.vimm.net/download/?mediaId=$mediaId
		headers=$(curl -sI -X GET -H "Referer: https://vimm.net/vault/$vaultId" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" --insecure $url)
		gameName=$(echo "$headers" | grep -o -E "filename=.*" | cut -d'=' -f2 | cut -d'"' -f2)
	fi
	sleep 1
}

So I’m not sure this is the problem…

**Comment by trtuanpham** [comment]
In my case I had to change that there was no “/download” for it to work
Update: I downloaded gameboy advance roms

**Comment by Vitty85** [comment]
Ok I got it, I will try to update it and test.

**Comment by Vitty85** [comment]
Fixed in last 1.7 release: https://github.com/Vitty85/vimm-client-miyoo/releases/download/1.7/MiyooVimmClient.zip

**Comment by Vitty85** [comment]
Fixed in last 1.7 release: https://github.com/Vitty85/vimm-client-miyoo/releases/download/1.7/MiyooVimmClient.zip
